# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2563f0dbb282dd3898a4966651b6f102b3c0b8fb30c73867fb8888d27cb0d82c1fb476781950b3ee1e986b630d1c1098f0720fc0c6f257f72602acc5e3b1b40

test:
  secret_key_base: 9cb1dbb2238575382d61aba9230dc43d46ce4a923c9b3270d2159ba9175feb4f7dac5344450006f97a883d21e36fff0dd9c2b3a9cf682dc37fd8c8e5a961e0a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
